/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.niton.todo;

import com.niton.reactj.ReactiveController;
import com.niton.todo.ui.TodoView;

import javax.swing.*;
import java.awt.*;

public class App {

    public static void main(String[] args) {
        TodoView view = new TodoView();
        TodoView view2 = new TodoView();
        TodoTask task = new TodoTask("Clean the dishes","Mom told me to");

        ReactiveController<TodoController> controller = new ReactiveController<>(view,new TodoController());
        controller.bind(task);
        ReactiveController<TodoController> controller2 = new ReactiveController<>(view2,new TodoController());
        controller2.bind(task);

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.getContentPane().setLayout(new GridLayout());
        frame.getContentPane().add(view);
        frame.getContentPane().add(view2);
        frame.pack();
        frame.setVisible(true);

        while (true){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
            System.out.println(task);
        }
    }
}
